### ISSUE TITLE
Tests are failing due to etcd client API changes

### ISSUE THREAD

**Issue by orls** [duedil-ltd/discodns#38]
Travis builds are downloading the latest version of the `go-etcd` package, which targets etcd 2.0.x, but the build env and some of our tests assume etcd 0.4.6. This is the cause of the current travis build failures.

We should either [vendor in dependencies](https://github.com/tools/godep) fixed to the [v0.4.6 tag](https://github.com/coreos/go-etcd/tree/v0.4.6) or start fully targeting etcd 2

We should probably vendor deps soon anyway

**Comment by tarnfeld** [comment]
Why don't we use [dogeps](https://github.com/tools/godep).

**Comment by orls** [comment]
Fixed by #41
